<?php

return [
    'WOOCOMMERCE_STORE_URL' => env('WOOCOMMERCE_STORE_URL', 'http://localhoste'),
    'WOOCOMMERCE_CONSUMER_KEY' => env('WOOCOMMERCE_CONSUMER_KEY', ''),
    'WOOCOMMERCE_CONSUMER_SECRET' => env('WOOCOMMERCE_CONSUMER_SECRET', ''),
];
